# Generated by Django 5.2.6 on 2025-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eldlog',
            name='compliant',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
